CREATE database db_agenda_maven;

USE DB_AGENDA_MAVEN;

CREATE TABLE `contacto` (
	`ID_CONTACTO` SMALLINT(5) NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(40) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`APELLIDO` VARCHAR(40) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`FECHA_NACIMIENTO` DATE NULL DEFAULT NULL,
	`EMAIL` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`TELEFONO` INT(10) NULL DEFAULT NULL,
	`ESTADO` TINYINT(3) NOT NULL DEFAULT '1',
	`FECHA_CREACION` DATE NULL DEFAULT NULL,
	`FECHA_MODIFICACION` DATE NULL DEFAULT NULL,
	`FECHA_DESACTIVACION` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`ID_CONTACTO`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

INSERT INTO CONTACTO (NOMBRE,APELLIDO,FECHA_NACIMIENTO,EMAIL,TELEFONO,FECHA_CREACION) 

			VALUE    	("ALEJANDRO","CRUZ","1990-01-01","ALEJANDROCRUZ@MAIL.COM", 1156325589,CURDATE()),
					 		("ELSA","PATO","1992-01-01","ELSAPATO@MAIL.COM", 1156325478,CURDATE()),
                     ("ELVIS","TEK","1985-01-01","ELVISTEK@MAIL.COM", 1156325369,CURDATE()),
                     ("ARMANDO","PAREDES","1980-01-01","AMRANDOPAREDES@MAIL.COM", 1156325258,CURDATE()),
                     ("LUZ","ROJAS","1997-01-01","LUZROJAS@MAIL.COM", 1156325789,CURDATE());